from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 879)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.led_crindsend = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.led_crindsend.sizePolicy().hasHeightForWidth())
        self.led_crindsend.setSizePolicy(sizePolicy)
        self.led_crindsend.setMinimumSize(QtCore.QSize(10, 10))
        self.led_crindsend.setMaximumSize(QtCore.QSize(10, 10))
        self.led_crindsend.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.led_crindsend.setText("")
        self.led_crindsend.setObjectName("led_crindsend")
        self.horizontalLayout_7.addWidget(self.led_crindsend)
        self.led_crindreceive = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.led_crindreceive.sizePolicy().hasHeightForWidth())
        self.led_crindreceive.setSizePolicy(sizePolicy)
        self.led_crindreceive.setMinimumSize(QtCore.QSize(10, 10))
        self.led_crindreceive.setMaximumSize(QtCore.QSize(10, 10))
        self.led_crindreceive.setStyleSheet(
            "background-color: rgb(85, 255, 0);")
        self.led_crindreceive.setText("")
        self.led_crindreceive.setObjectName("led_crindreceive")
        self.horizontalLayout_7.addWidget(self.led_crindreceive)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.led_pumpsend = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.led_pumpsend.sizePolicy().hasHeightForWidth())
        self.led_pumpsend.setSizePolicy(sizePolicy)
        self.led_pumpsend.setMinimumSize(QtCore.QSize(10, 10))
        self.led_pumpsend.setMaximumSize(QtCore.QSize(10, 10))
        self.led_pumpsend.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.led_pumpsend.setText("")
        self.led_pumpsend.setObjectName("led_pumpsend")
        self.horizontalLayout_10.addWidget(self.led_pumpsend)
        self.led_pumpreceive = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.led_pumpreceive.sizePolicy().hasHeightForWidth())
        self.led_pumpreceive.setSizePolicy(sizePolicy)
        self.led_pumpreceive.setMinimumSize(QtCore.QSize(10, 10))
        self.led_pumpreceive.setMaximumSize(QtCore.QSize(10, 10))
        self.led_pumpreceive.setStyleSheet(
            "background-color: rgb(85, 255, 0);")
        self.led_pumpreceive.setText("")
        self.led_pumpreceive.setObjectName("led_pumpreceive")
        self.horizontalLayout_10.addWidget(self.led_pumpreceive)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_10)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        self.horizontalLayout_11.addLayout(self.horizontalLayout_9)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.dollars = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.dollars.sizePolicy().hasHeightForWidth())
        self.dollars.setSizePolicy(sizePolicy)
        self.dollars.setMinimumSize(QtCore.QSize(300, 75))
        self.dollars.setMaximumSize(QtCore.QSize(1000, 200))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.dollars.setFont(font)
        self.dollars.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                   "color: rgb(0, 0, 0);")
        self.dollars.setAlignment(QtCore.Qt.AlignCenter)
        self.dollars.setObjectName("dollars")
        self.verticalLayout.addWidget(self.dollars)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.gallons = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gallons.sizePolicy().hasHeightForWidth())
        self.gallons.setSizePolicy(sizePolicy)
        self.gallons.setMinimumSize(QtCore.QSize(300, 75))
        self.gallons.setMaximumSize(QtCore.QSize(1000, 200))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(36)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gallons.setFont(font)
        self.gallons.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                   "color: rgb(0, 0, 0);")
        self.gallons.setAlignment(QtCore.Qt.AlignCenter)
        self.gallons.setObjectName("gallons")
        self.verticalLayout.addWidget(self.gallons)
        self.verticalLayout_11.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_softkey_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_1.sizePolicy().hasHeightForWidth())
        self.btn_softkey_1.setSizePolicy(sizePolicy)
        self.btn_softkey_1.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_1.setText("")
        self.btn_softkey_1.setObjectName("btn_softkey_1")
        self.verticalLayout_3.addWidget(self.btn_softkey_1)
        self.btn_softkey_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_2.sizePolicy().hasHeightForWidth())
        self.btn_softkey_2.setSizePolicy(sizePolicy)
        self.btn_softkey_2.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_2.setText("")
        self.btn_softkey_2.setObjectName("btn_softkey_2")
        self.verticalLayout_3.addWidget(self.btn_softkey_2)
        self.btn_softkey_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_3.sizePolicy().hasHeightForWidth())
        self.btn_softkey_3.setSizePolicy(sizePolicy)
        self.btn_softkey_3.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_3.setText("")
        self.btn_softkey_3.setObjectName("btn_softkey_3")
        self.verticalLayout_3.addWidget(self.btn_softkey_3)
        self.btn_softkey_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_4.sizePolicy().hasHeightForWidth())
        self.btn_softkey_4.setSizePolicy(sizePolicy)
        self.btn_softkey_4.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_4.setText("")
        self.btn_softkey_4.setObjectName("btn_softkey_4")
        self.verticalLayout_3.addWidget(self.btn_softkey_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.screen = QtWidgets.QLabel(self.centralwidget)
        self.screen.setMinimumSize(QtCore.QSize(288, 288))
        self.screen.setMaximumSize(QtCore.QSize(288, 288))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.screen.setFont(font)
        self.screen.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.screen.setAlignment(QtCore.Qt.AlignCenter)
        self.screen.setObjectName("screen")
        self.horizontalLayout_5.addWidget(self.screen)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_softkey_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_5.sizePolicy().hasHeightForWidth())
        self.btn_softkey_5.setSizePolicy(sizePolicy)
        self.btn_softkey_5.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_5.setText("")
        self.btn_softkey_5.setObjectName("btn_softkey_5")
        self.verticalLayout_4.addWidget(self.btn_softkey_5)
        self.btn_softkey_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_6.sizePolicy().hasHeightForWidth())
        self.btn_softkey_6.setSizePolicy(sizePolicy)
        self.btn_softkey_6.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_6.setText("")
        self.btn_softkey_6.setObjectName("btn_softkey_6")
        self.verticalLayout_4.addWidget(self.btn_softkey_6)
        self.btn_softkey_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_7.sizePolicy().hasHeightForWidth())
        self.btn_softkey_7.setSizePolicy(sizePolicy)
        self.btn_softkey_7.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_7.setText("")
        self.btn_softkey_7.setObjectName("btn_softkey_7")
        self.verticalLayout_4.addWidget(self.btn_softkey_7)
        self.btn_softkey_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_softkey_8.sizePolicy().hasHeightForWidth())
        self.btn_softkey_8.setSizePolicy(sizePolicy)
        self.btn_softkey_8.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_softkey_8.setText("")
        self.btn_softkey_8.setObjectName("btn_softkey_8")
        self.verticalLayout_4.addWidget(self.btn_softkey_8)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.verticalLayout_2.addLayout(self.verticalLayout_11)
        self.btn_cardinsert = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_cardinsert.sizePolicy().hasHeightForWidth())
        self.btn_cardinsert.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_cardinsert.setFont(font)
        self.btn_cardinsert.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_cardinsert.setObjectName("btn_cardinsert")
        self.verticalLayout_2.addWidget(self.btn_cardinsert)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_key_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_1.sizePolicy().hasHeightForWidth())
        self.btn_key_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_1.setFont(font)
        self.btn_key_1.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_1.setObjectName("btn_key_1")
        self.verticalLayout_5.addWidget(self.btn_key_1)
        self.btn_key_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_4.sizePolicy().hasHeightForWidth())
        self.btn_key_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_4.setFont(font)
        self.btn_key_4.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_4.setObjectName("btn_key_4")
        self.verticalLayout_5.addWidget(self.btn_key_4)
        self.btn_key_7 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_7.sizePolicy().hasHeightForWidth())
        self.btn_key_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_7.setFont(font)
        self.btn_key_7.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_7.setObjectName("btn_key_7")
        self.verticalLayout_5.addWidget(self.btn_key_7)
        self.btn_key_clear = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_clear.sizePolicy().hasHeightForWidth())
        self.btn_key_clear.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_clear.setFont(font)
        self.btn_key_clear.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_key_clear.setObjectName("btn_key_clear")
        self.verticalLayout_5.addWidget(self.btn_key_clear)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.btn_key_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_2.sizePolicy().hasHeightForWidth())
        self.btn_key_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_2.setFont(font)
        self.btn_key_2.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_2.setObjectName("btn_key_2")
        self.verticalLayout_6.addWidget(self.btn_key_2)
        self.btn_key_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_5.sizePolicy().hasHeightForWidth())
        self.btn_key_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_5.setFont(font)
        self.btn_key_5.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_5.setObjectName("btn_key_5")
        self.verticalLayout_6.addWidget(self.btn_key_5)
        self.btn_key_8 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_8.sizePolicy().hasHeightForWidth())
        self.btn_key_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_8.setFont(font)
        self.btn_key_8.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_8.setObjectName("btn_key_8")
        self.verticalLayout_6.addWidget(self.btn_key_8)
        self.btn_key_0 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_0.sizePolicy().hasHeightForWidth())
        self.btn_key_0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_0.setFont(font)
        self.btn_key_0.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_0.setObjectName("btn_key_0")
        self.verticalLayout_6.addWidget(self.btn_key_0)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btn_key_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_3.sizePolicy().hasHeightForWidth())
        self.btn_key_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_3.setFont(font)
        self.btn_key_3.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_3.setObjectName("btn_key_3")
        self.verticalLayout_7.addWidget(self.btn_key_3)
        self.btn_key_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_6.sizePolicy().hasHeightForWidth())
        self.btn_key_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_6.setFont(font)
        self.btn_key_6.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_6.setObjectName("btn_key_6")
        self.verticalLayout_7.addWidget(self.btn_key_6)
        self.btn_key_9 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_9.sizePolicy().hasHeightForWidth())
        self.btn_key_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_9.setFont(font)
        self.btn_key_9.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_9.setObjectName("btn_key_9")
        self.verticalLayout_7.addWidget(self.btn_key_9)
        self.btn_key_ok = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_ok.sizePolicy().hasHeightForWidth())
        self.btn_key_ok.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_ok.setFont(font)
        self.btn_key_ok.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_ok.setObjectName("btn_key_ok")
        self.verticalLayout_7.addWidget(self.btn_key_ok)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_key_yes = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_yes.sizePolicy().hasHeightForWidth())
        self.btn_key_yes.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_yes.setFont(font)
        self.btn_key_yes.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_yes.setObjectName("btn_key_yes")
        self.verticalLayout_8.addWidget(self.btn_key_yes)
        self.btn_key_no = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_no.sizePolicy().hasHeightForWidth())
        self.btn_key_no.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_no.setFont(font)
        self.btn_key_no.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_key_no.setObjectName("btn_key_no")
        self.verticalLayout_8.addWidget(self.btn_key_no)
        self.btn_key_cancel = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_cancel.sizePolicy().hasHeightForWidth())
        self.btn_key_cancel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_cancel.setFont(font)
        self.btn_key_cancel.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_key_cancel.setObjectName("btn_key_cancel")
        self.verticalLayout_8.addWidget(self.btn_key_cancel)
        self.btn_key_help = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_key_help.sizePolicy().hasHeightForWidth())
        self.btn_key_help.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_key_help.setFont(font)
        self.btn_key_help.setStyleSheet(
            "background-color: rgb(200, 209, 197);")
        self.btn_key_help.setObjectName("btn_key_help")
        self.verticalLayout_8.addWidget(self.btn_key_help)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.nozzle = QtWidgets.QSlider(self.centralwidget)
        self.nozzle.setStyleSheet("")
        self.nozzle.setOrientation(QtCore.Qt.Vertical)
        self.nozzle.setObjectName("nozzle")
        self.horizontalLayout_3.addWidget(self.nozzle)
        self.verticalLayout_17.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.gradescreen_1 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gradescreen_1.sizePolicy().hasHeightForWidth())
        self.gradescreen_1.setSizePolicy(sizePolicy)
        self.gradescreen_1.setMinimumSize(QtCore.QSize(100, 50))
        self.gradescreen_1.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gradescreen_1.setFont(font)
        self.gradescreen_1.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                         "color: rgb(0, 0, 0);")
        self.gradescreen_1.setAlignment(QtCore.Qt.AlignCenter)
        self.gradescreen_1.setObjectName("gradescreen_1")
        self.verticalLayout_10.addWidget(self.gradescreen_1)
        self.btn_grade_1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_grade_1.sizePolicy().hasHeightForWidth())
        self.btn_grade_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_grade_1.setFont(font)
        self.btn_grade_1.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_grade_1.setObjectName("btn_grade_1")
        self.verticalLayout_10.addWidget(self.btn_grade_1)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gradescreen_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gradescreen_2.sizePolicy().hasHeightForWidth())
        self.gradescreen_2.setSizePolicy(sizePolicy)
        self.gradescreen_2.setMinimumSize(QtCore.QSize(100, 50))
        self.gradescreen_2.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gradescreen_2.setFont(font)
        self.gradescreen_2.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                         "color: rgb(0, 0, 0);")
        self.gradescreen_2.setAlignment(QtCore.Qt.AlignCenter)
        self.gradescreen_2.setObjectName("gradescreen_2")
        self.verticalLayout_12.addWidget(self.gradescreen_2)
        self.btn_grade_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_grade_2.sizePolicy().hasHeightForWidth())
        self.btn_grade_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_grade_2.setFont(font)
        self.btn_grade_2.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_grade_2.setObjectName("btn_grade_2")
        self.verticalLayout_12.addWidget(self.btn_grade_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.gradescreen_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gradescreen_3.sizePolicy().hasHeightForWidth())
        self.gradescreen_3.setSizePolicy(sizePolicy)
        self.gradescreen_3.setMinimumSize(QtCore.QSize(100, 50))
        self.gradescreen_3.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gradescreen_3.setFont(font)
        self.gradescreen_3.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                         "color: rgb(0, 0, 0);")
        self.gradescreen_3.setAlignment(QtCore.Qt.AlignCenter)
        self.gradescreen_3.setObjectName("gradescreen_3")
        self.verticalLayout_13.addWidget(self.gradescreen_3)
        self.btn_grade_3 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_grade_3.sizePolicy().hasHeightForWidth())
        self.btn_grade_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_grade_3.setFont(font)
        self.btn_grade_3.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_grade_3.setObjectName("btn_grade_3")
        self.verticalLayout_13.addWidget(self.btn_grade_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.gradescreen_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gradescreen_4.sizePolicy().hasHeightForWidth())
        self.gradescreen_4.setSizePolicy(sizePolicy)
        self.gradescreen_4.setMinimumSize(QtCore.QSize(100, 50))
        self.gradescreen_4.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gradescreen_4.setFont(font)
        self.gradescreen_4.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                         "color: rgb(0, 0, 0);")
        self.gradescreen_4.setAlignment(QtCore.Qt.AlignCenter)
        self.gradescreen_4.setObjectName("gradescreen_4")
        self.verticalLayout_14.addWidget(self.gradescreen_4)
        self.btn_grade_4 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_grade_4.sizePolicy().hasHeightForWidth())
        self.btn_grade_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_grade_4.setFont(font)
        self.btn_grade_4.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_grade_4.setObjectName("btn_grade_4")
        self.verticalLayout_14.addWidget(self.btn_grade_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gradescreen_5 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gradescreen_5.sizePolicy().hasHeightForWidth())
        self.gradescreen_5.setSizePolicy(sizePolicy)
        self.gradescreen_5.setMinimumSize(QtCore.QSize(100, 50))
        self.gradescreen_5.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gradescreen_5.setFont(font)
        self.gradescreen_5.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                         "color: rgb(0, 0, 0);")
        self.gradescreen_5.setText("")
        self.gradescreen_5.setAlignment(QtCore.Qt.AlignCenter)
        self.gradescreen_5.setObjectName("gradescreen_5")
        self.verticalLayout_15.addWidget(self.gradescreen_5)
        self.btn_grade_5 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_grade_5.sizePolicy().hasHeightForWidth())
        self.btn_grade_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_grade_5.setFont(font)
        self.btn_grade_5.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_grade_5.setObjectName("btn_grade_5")
        self.verticalLayout_15.addWidget(self.btn_grade_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_15)
        self.verticalLayout_16 = QtWidgets.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.gradescreen_7 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.gradescreen_7.sizePolicy().hasHeightForWidth())
        self.gradescreen_7.setSizePolicy(sizePolicy)
        self.gradescreen_7.setMinimumSize(QtCore.QSize(100, 50))
        self.gradescreen_7.setMaximumSize(QtCore.QSize(1000, 50))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.gradescreen_7.setFont(font)
        self.gradescreen_7.setStyleSheet("background-color: rgb(216, 216, 107);\n"
                                         "color: rgb(0, 0, 0);")
        self.gradescreen_7.setText("")
        self.gradescreen_7.setAlignment(QtCore.Qt.AlignCenter)
        self.gradescreen_7.setObjectName("gradescreen_7")
        self.verticalLayout_16.addWidget(self.gradescreen_7)
        self.btn_grade_6 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.btn_grade_6.sizePolicy().hasHeightForWidth())
        self.btn_grade_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        self.btn_grade_6.setFont(font)
        self.btn_grade_6.setStyleSheet("background-color: rgb(200, 209, 197);")
        self.btn_grade_6.setObjectName("btn_grade_6")
        self.verticalLayout_16.addWidget(self.btn_grade_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_16)
        self.verticalLayout_17.addLayout(self.horizontalLayout_2)
        self.verticalLayout_18.addLayout(self.verticalLayout_17)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "7-11 DexSimulator"))
        self.label_3.setText(_translate("MainWindow", "CRIND"))
        self.label_4.setText(_translate("MainWindow", "PUMP"))
        self.label.setText(_translate("MainWindow", "DOLLARS"))
        self.dollars.setText(_translate("MainWindow", "3.46"))
        self.label_2.setText(_translate("MainWindow", "GALLONS"))
        self.gallons.setText(_translate("MainWindow", "0.123"))
        self.screen.setText(_translate("MainWindow", "PLEASE PAY INSIDE"))
        self.btn_cardinsert.setText(_translate("MainWindow", "CARD INSERT"))
        self.btn_key_1.setText(_translate("MainWindow", "QZ\n"
                                          "1"))
        self.btn_key_4.setText(_translate("MainWindow", "GHI\n"
                                          "4"))
        self.btn_key_7.setText(_translate("MainWindow", "PRS\n"
                                          "7"))
        self.btn_key_clear.setText(_translate("MainWindow", "CLEAR"))
        self.btn_key_2.setText(_translate("MainWindow", "ABC\n"
                                          "2"))
        self.btn_key_5.setText(_translate("MainWindow", "JKL\n"
                                          "5"))
        self.btn_key_8.setText(_translate("MainWindow", "TUV\n"
                                          "8"))
        self.btn_key_0.setText(_translate("MainWindow", "0"))
        self.btn_key_3.setText(_translate("MainWindow", "DEF\n"
                                          "3"))
        self.btn_key_6.setText(_translate("MainWindow", "MNO\n"
                                          "6"))
        self.btn_key_9.setText(_translate("MainWindow", "WXY\n"
                                          "9"))
        self.btn_key_ok.setText(_translate("MainWindow", "ENTER\n"
                                           "OK"))
        self.btn_key_yes.setText(_translate("MainWindow", "YES\n"
                                            "RECEIPT"))
        self.btn_key_no.setText(_translate("MainWindow", "NO"))
        self.btn_key_cancel.setText(_translate("MainWindow", "CANCEL"))
        self.btn_key_help.setText(_translate("MainWindow", "HELP"))
        self.gradescreen_1.setText(_translate("MainWindow", "2.999"))
        self.btn_grade_1.setText(_translate("MainWindow", "GRADE 1"))
        self.gradescreen_2.setText(_translate("MainWindow", "3.999"))
        self.btn_grade_2.setText(_translate("MainWindow", "GRADE 2"))
        self.gradescreen_3.setText(_translate("MainWindow", "4.999"))
        self.btn_grade_3.setText(_translate("MainWindow", "GRADE 3"))
        self.gradescreen_4.setText(_translate("MainWindow", "5.999"))
        self.btn_grade_4.setText(_translate("MainWindow", "GRADE 4"))
        self.btn_grade_5.setText(_translate("MainWindow", "GRADE 5"))
        self.btn_grade_6.setText(_translate("MainWindow", "GRADE 6"))
