import sys
from pump import *
from carddetails import *


class MyWin(QtWidgets.QMainWindow, Ui_MainWindow):
    def __init__(self, parent=None):
        QtWidgets.QWidget.__init__(self, parent)
        self.setupUi(self)
        self.disablebuttons()
        self.btn_cardinsert.clicked.connect(self.openDialog)

    def openDialog(self):
        dialog = QtWidgets.QDialog()
        dialog.ui = Ui_Dialog()
        dialog.ui.setupUi(dialog)
        dialog.exec_()
        dialog.show()

    def disablebuttons(self):
        self.btn_cardinsert.setEnabled(False)
        self.btn_cardinsert.setStyleSheet("background-color: Silver")
        self.btn_softkey_1.setEnabled(False)
        self.btn_softkey_1.setStyleSheet("background-color: Silver")
        self.btn_softkey_2.setEnabled(False)
        self.btn_softkey_2.setStyleSheet("background-color: Silver")
        self.btn_softkey_3.setEnabled(False)
        self.btn_softkey_3.setStyleSheet("background-color: Silver")
        self.btn_softkey_4.setEnabled(False)
        self.btn_softkey_4.setStyleSheet("background-color: Silver")
        self.btn_softkey_5.setEnabled(False)
        self.btn_softkey_5.setStyleSheet("background-color: Silver")
        self.btn_softkey_6.setEnabled(False)
        self.btn_softkey_6.setStyleSheet("background-color: Silver")
        self.btn_softkey_7.setEnabled(False)
        self.btn_softkey_7.setStyleSheet("background-color: Silver")
        self.btn_softkey_8.setEnabled(False)
        self.btn_softkey_8.setStyleSheet("background-color: Silver")
        self.btn_key_1.setEnabled(False)
        self.btn_key_1.setStyleSheet("background-color: Silver")
        self.btn_key_2.setEnabled(False)
        self.btn_key_2.setStyleSheet("background-color: Silver")
        self.btn_key_3.setEnabled(False)
        self.btn_key_3.setStyleSheet("background-color: Silver")
        self.btn_key_4.setEnabled(False)
        self.btn_key_4.setStyleSheet("background-color: Silver")
        self.btn_key_5.setEnabled(False)
        self.btn_key_5.setStyleSheet("background-color: Silver")
        self.btn_key_6.setEnabled(False)
        self.btn_key_6.setStyleSheet("background-color: Silver")
        self.btn_key_7.setEnabled(False)
        self.btn_key_7.setStyleSheet("background-color: Silver")
        self.btn_key_8.setEnabled(False)
        self.btn_key_8.setStyleSheet("background-color: Silver")
        self.btn_key_9.setEnabled(False)
        self.btn_key_9.setStyleSheet("background-color: Silver")
        self.btn_key_0.setEnabled(False)
        self.btn_key_0.setStyleSheet("background-color: Silver")
        self.btn_key_yes.setEnabled(False)
        self.btn_key_yes.setStyleSheet("background-color: Silver")
        self.btn_key_no.setEnabled(False)
        self.btn_key_no.setStyleSheet("background-color: Silver")
        self.btn_key_cancel.setEnabled(False)
        self.btn_key_cancel.setStyleSheet("background-color: Silver")
        self.btn_key_help.setEnabled(False)
        self.btn_key_help.setStyleSheet("background-color: Silver")
        self.btn_key_ok.setEnabled(False)
        self.btn_key_ok.setStyleSheet("background-color: Silver")
        self.btn_key_clear.setEnabled(False)
        self.btn_key_clear.setStyleSheet("background-color: Silver")
        self.btn_grade_1.setEnabled(False)
        self.btn_grade_1.setStyleSheet("background-color: Silver")
        self.btn_grade_2.setEnabled(False)
        self.btn_grade_2.setStyleSheet("background-color: Silver")
        self.btn_grade_3.setEnabled(False)
        self.btn_grade_3.setStyleSheet("background-color: Silver")
        self.btn_grade_4.setEnabled(False)
        self.btn_grade_4.setStyleSheet("background-color: Silver")
        self.btn_grade_5.setEnabled(False)
        self.btn_grade_5.setStyleSheet("background-color: Silver")
        self.btn_grade_6.setEnabled(False)
        self.btn_grade_6.setStyleSheet("background-color: Silver")
